### PR TITLE
add a mutex on the physical memory mmapping

### PR DESCRIPTION
**Pull request by eloi29**
The physical memory is mmapped / munmapped to memory in order to be
allocated or copied.  The use of a mutual exclusion avoid concurrent
access during those memory manipulations.

Signed-off-by: Eloi BAIL <eloi.bail@savoirfairelinux.com>

### CODE REVIEW

**Comment by clopez** [comment]
Does this fix a crash or something else?

**Comment by eloi29** [comment]
Yes.
With a complex pipeline with tee branches, this assertion systematically occurs: https://github.com/Freescale/gstreamer-imx/blob/master/src/ipu/allocator.c#L104

After investigating, I saw that the mapped_virt_addr was already used during the a copy (gst_imx_phys_mem_allocator_copy).
Adding a mutex ensure that the virtual address has been correctly released before doing an other mmap.

**Comment by dv1** [comment]
Oh, good catch! I think it would be better though if the GMutex were part of the allocator, and not a global variable. Could you modify your patch that way? Remember to initialize a GMutex member variable with g_mutex_init() and finalize it with g_mutex_clear() !

**Comment by eloi29** [comment]
I am working on that dv1. Let me test it again and post it

**Comment by sdroege** [comment]
Any news on this?

**Comment by eloi29** [comment]
Hi Sebastien, 

I will try to implement modifications requested by @dv1 ASAP. Quite in rush ATM.

**Comment by moberhuber** [comment]
Any news on this? - I'm getting a SEGV on following backtrace occasionally, using gstreamer-imx-0.13.0 with gstreamer-1.14.4 and I'm wondering if it might be related. Or would I need #228 / #229 ?
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  memcpy () at ../sysdeps/arm/armv7/multiarch/memcpy_impl.S:568
568	../sysdeps/arm/armv7/multiarch/memcpy_impl.S: No such file or directory.
(gdb) bt
#0  memcpy () at ../sysdeps/arm/armv7/multiarch/memcpy_impl.S:568
#1  0x76180158 in gst_imx_phys_mem_allocator_copy (mem=0x74806d10, offset=0, size=2048) at ../src/common/phys_mem_allocator.c:262
#2  0x76bba258 in gst_memory_make_mapped (mem=mem@entry=0x74806d10, info=info@entry=0x74725a34, flags=flags@entry=GST_MAP_WRITE) at gstmemory.c:242
#3  0x76b7a294 in gst_buffer_map_range (buffer=0x473208, idx=idx@entry=0, length=1, length@entry=-1, info=info@entry=0x74725a34, 
    flags=flags@entry=GST_MAP_WRITE) at gstbuffer.c:1738
#4  0x76b7a4f4 in gst_buffer_map (buffer=<optimized out>, info=info@entry=0x74725a34, flags=flags@entry=GST_MAP_WRITE) at gstbuffer.c:1677
#5  0x75f9ed68 in gst_imx_ipu_blitter_fill_region (blitter=blitter@entry=0x470660, region=region@entry=0x47085c, color=4278190080)
    at ../src/ipu/blitter.c:398
#6  0x75f9ef00 in gst_imx_ipu_blitter_blit (blitter=0x470660, alpha=<optimized out>) at ../src/ipu/blitter.c:425
#7  0x75f86fa4 in gst_imx_blitter_video_transform_transform_frame (transform=0x460150, in=0x7480c498, out=0x7480c5d8)
    at ../src/blitter/video_transform.c:1350
#8  0x76cda300 in default_generate_output (trans=0x460150, outbuf=0x74725bbc) at gstbasetransform.c:2132
#9  0x76cd9a84 in gst_base_transform_chain (pad=<optimized out>, parent=0x460150, buffer=<optimized out>) at gstbasetransform.c:2285
#10 0x76bc27e4 in gst_pad_chain_data_unchecked (data=0x7480c498, type=4112, pad=0x45a210) at gstpad.c:4322
#11 gst_pad_push_data (pad=pad@entry=0x45a0b8, type=type@entry=4112, data=data@entry=0x7480c498) at gstpad.c:4578
#12 0x76bcbe98 in gst_pad_push (pad=pad@entry=0x45a0b8, buffer=0x7480c498) at gstpad.c:4697
#13 0x76cd3790 in gst_base_src_loop (pad=0x45a0b8) at gstbasesrc.c:2957
```

**Comment by dv1** [comment]
The new v2 version of gstreamer-imx no longer uses this allocator, so this no longer applies.

**Pull request closed without merging**
