### PR TITLE
v4l2src:  	simplify determination of fps

### PR DESCRIPTION
**Pull request by sasamy**

### CODE REVIEW

**Comment by sasamy** [comment]
tested on CSI:adv7180 and PCIe:tw6869, PAL and NTSC

**Comment by sdroege** [comment]
@dv1 @sasamy The second commit is breaking the v4l2src with drivers that can actually support different framerates. I assume this was only tested with drivers that could do PAL and NTSC and nothing else, but it is generally wrong. The previous probing code should've resulted in the correct values for the driver we're using here and as such allowed other framerates.

Can this be reverted?

**Comment by sasamy** [comment]
@sdroege 

> The second commit is breaking the v4l2src with drivers that can actually support different framerates. I assume this was only tested with drivers that could do PAL and NTSC and nothing else, but it is generally wrong. 

All known standards are two groups with a frame rate of 30 fps and 25 fps respectively

#define V4L2_STD_ALL            (V4L2_STD_525_60	|\
				 V4L2_STD_625_50)

https://elixir.bootlin.com/linux/latest/source/include/uapi/linux/videodev2.h#L1263

PAL standard is included in the V4L2_STD_625_50 group

https://elixir.bootlin.com/linux/latest/source/include/uapi/linux/videodev2.h#L1254

NTSC - from the group V4L2_STD_525_60

https://elixir.bootlin.com/linux/latest/source/include/uapi/linux/videodev2.h#L1249

so I think that's enough for test

> The previous probing code should've resulted in the correct values for the driver we're using here and as such allowed other framerates.

the previous code has always determined 30 fps on the Linux kernel from NXP (CSI + adv7180 drivers)

**Comment by sdroege** [comment]
> the previous code has always determined 30 fps on the Linux kernel from NXP (CSI + adv7180 drivers)

Even if the driver did not report any standard at all?

**Comment by sasamy** [comment]
> Even if the driver did not report any standard at all?

Not sure in this case - I need some time to check it, but it incorrectly determines 30 fps if the PAL standard is known

https://github.com/Freescale/gstreamer-imx/issues/72

**Pull request merged**
