### PR TITLE
Add imxg2dpango plugin

### PR DESCRIPTION
**Pull request by bmx666**
This plugin is based on pango plugins: textoverlay, timeoverlay, clockoverlay and textrender. It use G2D for blit text with video frame.

### CODE REVIEW

**Comment by dv1** [comment]
Thanks for this. Sorry about my inactivity, I am involved in several projects at the moment, and time is short.. I agree this element is useful, but I keep thinking that the real solution would be to have some sort of hook for compositing in GStreamer. Perhaps a new GstQueue type that video elements can use to query for a compositor. Because, having to duplicate things like the compositor element and this element seems like the wrong approach. At the moment though there is most likely no other way to do it..

**Comment by sunkers** [comment]
Hello,
I have gstreamer-1.8.3 installed on my I.mx6 platform
I've run >> ./waf configure --prefix=/usr/lib/arm-linux-gnueabihf/gstreamer-1.0

But the project doesn't build : 

Setting top to                           : /IMX_UPDATE 
Setting out to                           : /IMX_UPDATE/build 
Checking for 'gcc' (C compiler)          : /usr/bin/gcc 
Checking for compiler switch -O2         : yes 
Checking for compiler switch -DPIC       : yes 
Checking for compiler switch -fPIC       : yes 
Checking for compiler switch -std=gnu99  : yes 
Checking for compiler switch -Wall       : yes 
Checking for compiler switch -Wextra     : yes 
Checking for compiler switch -Wno-sign-compare : yes 
Checking for compiler switch -Wno-missing-field-initializers : yes 
Checking for compiler switch -Wno-unused-parameter           : yes 
Checking for compiler switch -Wno-cpp                        : yes 
Building for Android                                         : no 
Checking for library dl                                      : yes 
Checking for library m                                       : yes 
Checking for library pthread                                 : yes 
Checking for program 'pkg-config'                            : /usr/bin/pkg-config 
Checking for 'gstreamer-1.0' version                         : yes 
Checking for 'gstreamer-1.0 >= 1.2.0'                        : yes 
Checking for 'gstreamer-base-1.0 >= 1.2.0'                   : yes 
Checking for 'gstreamer-audio-1.0 >= 1.2.0'                  : yes 
Checking for 'gstreamer-video-1.0 >= 1.2.0'                  : yes 
Checking for 'gstreamer-bad-allocators-1.0'                  : not found 
Checking for library gstphotography-1.0                      : yes 
Checking for 'pango >= 1.40.0'                               : not found 
Checking for 'cairo >= 1.14.0'                               : not found 
Checking for 'pangocairo >= 1.40.0'                          : not found 
checking whether or not the kernel version is greater than 3.5.0 : yes 
Checking for library g2d                                         : not found 
G2D elements will not be built - headers and/or libraries not found 
checking for linux/pxp_device.h                                  : no 
PxP elements will not be built - headers not found 
checking for linux/fb.h and the IPU header linux/ipu.h           : no 
IPU elements will not be built - headers not found 
Checking for 'libimxvpuapi >= 0.10.3'                            : not found 
could not find installed imxvpuapi library - VPU elements will not be built 
Checking for library X11                                         : yes 
Checking for header X11/Xlib.h                                   : yes 
Checking for library ['EGL']                                     : yes 
Checking for header EGL/egl.h                                    : yes 
Checking for library GLESv2                                      : yes 
Checking for header GLES2/gl2.h                                  : yes 
Checking for header ['GLES2/gl2.h', 'GLES2/gl2ext.h']            : yes 
EGL sink with Vivante direct textures will be built 
Selected EGL platform: x11 
Checking for 'libfslaudiocodec'                                  : yes 
Searching fslcodec plugin directory                              : found 
uniaudio decoder will be built 
Checking for library _mp3_enc_arm12_elinux                       : yes 
mp3 encoder will be built 
G2D Pango elements will not be built - pango, cairo, pangocairo packages not found 
'configure' finished successfully (7.837s)


I don't understand why the configure can't file the headers because they currently are installed

**Comment by bmx666** [comment]
@sunkers

> Checking for 'pango >= 1.40.0' : not found
> Checking for 'cairo >= 1.14.0' : not found
> Checking for 'pangocairo >= 1.40.0' : not found

**Comment by sunkers** [comment]
Thanks for the fast reply

root@nitrogen:/IMX_UPDATE# gst-inspect-1.0 |grep pango
pango:  textoverlay: Text overlay
pango:  timeoverlay: Time overlay
pango:  clockoverlay: Clock overlay
pango:  textrender: Text renderer

root@nitrogen:/IMX_UPDATE# gst-inspect-1.0 |grep cairo
cairo:  cairooverlay: Cairo overlay

and the vpuapi is supposed to be installed on the system

**Comment by bmx666** [comment]
@sunkers 
For Ubuntu or Debian you must install dev-packages with headers
libpango-dev, libcairo-dev, libpangocairo-dev, libimxvpuapi-dev

**Comment by sunkers** [comment]
The installation needs a 1.40 pango/cairo lib version, but i can't find higher than 1.38

**Comment by sunkers** [comment]
>>
Checking for 'gstreamer-bad-allocators-1.0'                  : not found 
Checking for library gstphotography-1.0                      : yes 
Checking for 'pango >= 1.40.0'                               : yes 
Checking for 'cairo >= 1.14.0'                               : yes 
Checking for 'pangocairo >= 1.40.0'                          : yes 
checking whether or not the kernel version is greater than 3.5.0 : yes 
Checking for library g2d                                         : not found 
G2D elements will not be built - headers and/or libraries not found 
checking for linux/pxp_device.h                                  : no 
PxP elements will not be built - headers not found 
checking for linux/fb.h and the IPU header linux/ipu.h           : no 
IPU elements will not be built - headers not found 
Checking for 'libimxvpuapi >= 0.10.3'                            : yes 
found installed imxvpuapi library - VPU elements will be built 
Checking for library X11                                         : yes 
Checking for header X11/Xlib.h                                   : yes 
Checking for library ['EGL']                                     : yes 
Checking for header EGL/egl.h                                    : yes 
Checking for library GLESv2                                      : yes 
Checking for header GLES2/gl2.h                                  : yes 
Checking for header ['GLES2/gl2.h', 'GLES2/gl2ext.h']            : yes 
EGL sink with Vivante direct textures will be built 
Selected EGL platform: x11 
Checking for 'libfslaudiocodec'                                  : yes 
Searching fslcodec plugin directory                              : found 
uniaudio decoder will be built 
Checking for library _mp3_enc_arm12_elinux                       : yes 
mp3 encoder will be built 
Checking for library g2d                                         : not found 
G2D Pango elements will not be built - pango, cairo, pangocairo packages not found 
'configure' finished successfully (8.721s)

Thanks for having resolved this, but there's still missing elements

**Comment by bmx666** [comment]
@sunkers
Add include Linux Kernel Headers

**Comment by sunkers** [comment]
The only error left is about the G2D library
I ran ./waf configure --disable-g2d --disable-pxp --disable-ipu --prefix=/usr/lib/arm-linux-gnueabihf/gstreamer-1.0 since i don't need to install the other ones

**Comment by sunkers** [comment]
I figured out how to build correctly on ubuntu because i work on it, but after configure / build / installation, i have several issues, including this one : 

`ubuntu@nitrogen:~/IMX_UPDATE$ gst-launch-1.0 -v imxv4l2videosrc device=/dev/video1 ! imxg2dtextoverlay text='Test' ! videoconvert ! autovideosink
WARNING: erroneous pipeline: could not link imxv4l2videosrc0 to imxg2dtextoverlay0
`
Do you have an idea where does this come from ?

**Comment by bmx666** [comment]
@sunkers, add imxiputransformer between imxv4l2videosrc and imxg2dtextoverlay for colorspace converting

**Comment by sunkers** [comment]
@bmx666 Thanks for the reply,
I'm currently reinstalling the i.mx6 board because there was a lot of duplicated libraries because i didn't specify the installation path once, and there was a lot of conflicts. 
Even with ./waf uninstall didn't work, and i couldn't achieve a full uninstallation
Btw it was my first time with ubuntu and gstreamer so i was a little confused when i first configured it, so no problem.
Could you explain me briefly why i need to add the imxiputransformer between imxv4l2videosrc and imxg2dtextoverlay ?
Thank you very much for all the answers by the way.

**Comment by bmx666** [comment]
@sunkers, read gstreamer's mans about sink <-> src, how it's work, and what need for construct efficent pipeline

> Could you explain me briefly why i need to add the imxiputransformer between imxv4l2videosrc and imxg2dtextoverlay ?

I already written it - for **colorspace converting**. **imxg2dtextoverlay** accept only input frames with RGB-color format, because G2D engine can blend 2 layers in RGB format only.

type command and look caps format for src and sink
> gst-inspect-1.0 imxg2dtextoverlay
> gst-inspect-1.0 imxv4l2videosrc

Simple trace most problems in gstreamer:
> **GST_DEBUG=2,*imxg2dpango*:9 gst-launch-1.0 -v ...**

My pipeline for test PAL camera with textoverlay and show on screen:
> gst-launch-1.0 imxv4l2videosrc device=/dev/video0 imx-capture-mode=3 queue-size=8 fps-n=25 ! imxipuvideotransform ! 'video/x-raw,width=720,height=576,format=RGBx' ! imxg2dtextoverlay valignment=top text="123" shaded-background=true ! imxipuvideotransform ! 'video/x-raw,width=720,height=576,format=NV12' ! imxg2dvideosink sync=false framebuffer=/dev/fb0

**Comment by aduskett** [comment]
I just want to thank you for providing this and saving me a ton of effort, crying, and work!

**Comment by aduskett** [comment]
I just want to thank you for providing this and saving me a ton of effort, crying, and work!
That being said, I was wondering if you could help me out.

I am using your plugin with no framebuffer output, and an ov5640 connected to the MIPI bus.
With the pipeline:

board: 
gst-launch-1.0 -ev imxv4l2videosrc device=/dev/video0 imx-capture-mode=4 ! imxipuvideotransform ! 'video/x-raw,width=1280,height=720,format=RGBx' ! imxg2dtextoverlay font-desc=DejaVuSans text="Hello world!" ! imxipuvideotransform ! 'video/x-raw,width=1280,height=720,format=NV12' ! imxvpuenc_h264 bitrate=10000 ! h264parse ! rtph264pay pt=97 ! rtprtxqueue ! udpsink port=5000 host=10.10.151.141 ts-offset=0

client:
gst-launch-1.0 -v rtpbin name=rtpbin rtp-profile=avpf latency=250 do-retransmission=1 udpsrc caps="application/x-rtp,media=(string)video,clock-rate=(int)90000,encoding-name=(string)H264" port=5000 ! rtpbin.recv_rtp_sink_0  rtpbin. ! rtph264depay ! avdec_h264 ! videoconvert ! autovideosink


I get a 720p image with "Hello world!" printed on the bottom over an RTP stream, however, it's... not as smooth as I would have hoped.

And with 1080p it becomes very very laggy.  I was hoping with the GPU rendering the text that it would be a lot smoother.  Any insights as to what I am doing wrong?

Thanks!

**Comment by DuBistKomisch** [comment]
I'm trying to get subtitles working with this. Turns out `subtitleoverlay` is hard coded to use `textoverlay`, so I added `imxg2dtextoverlay` and recompiled, and increased the rank of `imxg2dtextoverlay` in here and recompiled, which all works.

But when I try using `playbin` with URLs pointing to a standard 720p h264/aac mp4 YouTube video and corresponding vtt subtitles pulled out of `youtube-dl`, I just get memory errors over and over again:

```
0:00:02.908292001  9293  0x1fd3e30 ERROR            imxg2dpango basetextoverlay.c:2262:gst_imx_g2d_base_text_overlay_blend_g2d:<overlay> video frame data is not contiguous physical memory
```

So I'm basically at a brick wall here. The autoplugged pipeline is pretty much `imxvpudec` -> `imxg2dtextoverlay` -> `imxg2dvideosink` so seems like it should work. Any ideas?

Can't use normal `textoverlay` as the text bleeds out between keyframes, but works fine with a software decoder with terrible performance, as I'm sure you all know.

P.S. someone has thought about a more general solution to this hardware decoding + overlay problem, but I don't think any implementation has started: https://gstreamer.freedesktop.org/documentation/design/subtitle-overlays.html

**Comment by bmx666** [comment]
@DuBistKomisch, it's happened when you try blends frames from not contiguous physical memory, because i.MX6 G2D required frames allocated in physical memory only.
You can use workaround: preallocate contiguous physical memory somewhere in pipelines elements and then pass this frames into imxg2dtextoverlay.

**Comment by DuBistKomisch** [comment]
@bmx666 Thanks. I believe the videosink does the allocation in this sort of pipeline. What exactly does "aligned" mean anyway? I notice it seems to allocate 10 or so separate chunks of memory with `GST_DEBUG=imx*:4`, does it just need to allocate one big chunk instead?

**Comment by DuBistKomisch** [comment]
So I dumped a `playbin` pipeline [using dot files](https://developer.ridgerun.com/wiki/index.php/How_to_generate_a_Gstreamer_pipeline_diagram_\(graph\)) and constructed a similar but stripped down one manually, swapping in the `imx*` elements:

```
gst-launch-1.0 \
  filesrc location=spongebob.mkv ! matroskademux name=demux \
  demux. ! queue ! h264parse ! imxvpudec ! imxipuvideotransform ! queue ! over. \
  demux. ! queue ! over. \
  imxg2dtextoverlay name=over ! imxg2dvideosink \
  demux. ! queue ! aacparse ! avdec_aac ! audioconvert ! alsasink
```

...and this does work perfectly, so I think I might have to drop down to `decodebin` or similar and take over all of the `playsink` side. Not sure if I'd have to detect software decoded video and switch back to normal elements in that case. I'll post if I find anything else interesting.

**Comment by bmx666** [comment]
@DuBistKomisch 

> What exactly does "contiguous" mean here anyway?

Part of RAM used for inernal purpose, direct access to physical address exclude virtual remapping

**Comment by DuBistKomisch** [comment]
I managed to get it working by hacking the playback elements to use the imx elements. Maybe we also need `imxplaybin` etc in addition to these pango one? 🤦‍♂️ 

Here's [the diff](https://gist.github.com/DuBistKomisch/0427e88b1ec9eddbd264ec52eace2f84), then you need to remove `soft-colorbalance` and `deinterlace` from the default `playbin` `flags`.

**Pull request merged**
